In [ ]:
#Author : Bemnet Girma
#Roll No. 2164006
#KiiT University, Bhubanewar
#Program : MTech in Data Analytics
#Subject : Business Analytics Intelligence
#Lab Assignment Week three

In [2]:
#Q1: Create 1-D array having 10 elements, find the dimensions of the array and sort the array elements in ascending order using Numpy

import numpy as np
#Creating 1-D array having 10 element
arr = np.array([1,2,3,4,5,6,7,8,9,0])

#Find the dimension of the array
print(arr.ndim,"Dimensional Array")

# sort the array elements in ascending order using Numpy
arr = np.sort(arr)

print(arr)

1 Dimensional Array
[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Q2: Merge two array and display elements using Numpy

import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,2])
merged_array = np.append(arr1,arr2)

print("Array One =", arr1)
print("Array Two =", arr2)
print("Merged Array =", merged_array)

Array One = [1 2 3 4 5 6]
Array Two = [5 6 7 8 9 2]
Merged Array = [1 2 3 4 5 6 5 6 7 8 9 2]


In [7]:
#Q3: Create two 2D array , perform, +, -, *

import numpy as np

arr1 = np.array([[10,2,7],[8,5,11],[2,10,8]])
arr2 = np.array([[30,12,14],[16,50,44],[92,80,72]])

#Adddition of two array
added_array = arr1+arr2
print("Addition of an array")
print(added_array)
print("\n")

#substractionof two array
substracted_array = arr2-arr1
print("Substraction of an array")
print(substracted_array)
print("\n")

#Dividing an array
divided_array = arr2/arr1
print("Dividing an array")
print(divided_array)
print("\n")

#Multiplication of an array
multiplied_array = np.dot(arr1,arr2)
print("Multiplications of an array")
print(multiplied_array)
print("\n")

Addition of an array
[[40 14 21]
 [24 55 55]
 [94 90 80]]


Substraction of an array
[[20 10  7]
 [ 8 45 33]
 [90 70 64]]


Dividing an array
[[ 3.  6.  2.]
 [ 2. 10.  4.]
 [46.  8.  9.]]


Multiplications of an array
[[ 976  780  732]
 [1332 1226 1124]
 [ 956 1164 1044]]




In [9]:
#Q4: Create 1-D array, find out sum, max element, min element, mean

import numpy as np
arr = np.array([10,12,34,45,63,16])

#Find ou the sum of each element
sum = 0 
i = 0
for i in range(0,len(arr)):
    sum = sum + arr[i]
print(f"\n The sum of each element: {sum}")

#Max element
MAX = arr[0]
for i in range(0, len(arr)):
    if MAX<arr[i]:
        MAX = arr[i]
    else:
        continue
print(f"\nThe maximum element is {MAX}")

#MIN element
MIN = arr[0]
for i in range(0, len(arr)):
    if MIN>arr[i]:
        MIN = arr[i]
    else:
        continue
print(f"\nThe minimum element is {MAX}")

#MEAN of elemen
res=0
for i in range(0, len(arr)):
    res = res+arr[i]
mean = res/len(arr)
print(f"\nThe mean of element is {mean}")


 The sum of each element: 180

The maximum element is 63

The minimum element is 63

The mean of element is 30.0


In [10]:
#Q5: Find factorial using numpy library

import numpy as np
num = int(input("enter the number:"))
res = np.math.factorial(num)
print(f"The factorial of {num} is {res}")

enter the number:3
The factorial of 3 is 6


In [12]:
#Q6: generate random array having dimensions of 3*4

import numpy as np
rand_array= np.random.randint(1,10, size=(3,4))
print(rand_array)

[[6 8 1 3]
 [6 3 4 3]
 [9 9 9 5]]


In [13]:
#Q7: copy one array to another, search an element from the array

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10]);

print("Original Array:",arr)

#copy an array
arr_copy = np.copy(arr)
print("Copied Array:",arr)


num = int(input("search a number from 1-10:"))
for i in range(0,len(arr)):
    if num == arr[i]:
        print(f"The number {num} is found at {i} index")
        break
    else:
        continue

search a number from 1-10:4
The number 4 is found at 3 index
