# Week 04
### Author : Bemnet Girma
### Roll No. 2164006
### KiiT University, Bhubanewar
### Program : MTech in Data Analytics
### Subject : Business Analytics Intelligence
### Lab Assignment Week Four

#### 1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data 

In [3]:
import pandas as pd

# create Pandas array with dtype integer
pd_arr = pd.array(data=[1,2,3,4,5],dtype=int)
  
# print the formed array
print(pd_arr)

<PandasArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: int32


#### 2. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [6]:
# create Pandas array with dtype integer
pd_arr1 = pd.array(data=[1,2,3,4,5],dtype=int)
pd_arr2 = pd.array(data=[11,44,33,44,55],dtype=int)
  
# print the formed array
print("Pandas Array One", pd_arr1)
print("Pandas Array Two", pd_arr2)

print("Add Result:", pd_arr2+pd_arr1)
print("Subtract Result:", pd_arr2-pd_arr1)
print("Multiply Result:", pd_arr2*pd_arr1)
print("Divide Result:", pd_arr2/pd_arr1)

Pandas Array One <PandasArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: int32
Pandas Array Two <PandasArray>
[11, 44, 33, 44, 55]
Length: 5, dtype: int32
Add Result: <PandasArray>
[12, 46, 36, 48, 60]
Length: 5, dtype: int32
Subtract Result: <PandasArray>
[10, 42, 30, 40, 50]
Length: 5, dtype: int32
Multiply Result: <PandasArray>
[11, 88, 99, 176, 275]
Length: 5, dtype: int32
Divide Result: <PandasArray>
[11.0, 22.0, 11.0, 11.0, 11.0]
Length: 5, dtype: float64


#### 3. Write a Pandas program to convert a NumPy array to a Pandas series.( For example:
NumPy array:
[10 20 30 40 50]

Converted Pandas series:

0 10

1 20

2 30

3 40

4 50

In [9]:
import numpy as np
#Creating 1-D array having 5 element
arr = np.array([10,20,30,40,50])

print("NumPy Array", arr)

# converting the NumPy array 
# to a Pandas series
series = pd.Series(arr) 
  
# displaying the Pandas series
print("Pandas Series : ")
display(series)

NumPy Array [10 20 30 40 50]
Pandas Series : 


0    10
1    20
2    30
3    40
4    50
dtype: int32

#### 4. Write a Pandas program to convert the first column of a DataFrame as a Series.
(Example: Sample Output:

Original DataFrame

col1 col2 col3

0 1 4 7

1 2 5 5

2 3 6 8

3 4 9 12

4 7 5 1

5 11 0 11

1st column as a Series:

0 1

1 2

2 3

3 4

4 7

5 11

In [13]:
my_array = np.array([[1,4,7],[2,5,5],[3,6,8],[4,9,12],[7,5,1],[11,0,11]])

print(my_array)

df = pd.DataFrame(my_array, columns = ['col1','col2','col3'])

print(df)

my_series = df['col1'].squeeze()

display(my_series)

print(type(my_series))

[[ 1  4  7]
 [ 2  5  5]
 [ 3  6  8]
 [ 4  9 12]
 [ 7  5  1]
 [11  0 11]]
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11


0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int32

<class 'pandas.core.series.Series'>


#### 5. Write a Pandas program to convert a given Series to an array.
( Example:
Sample Output:

Original Data Series:

0 100

1 200

2 python

3 300.12

4 400

dtype: object

Series to an array

['100' '200' 'python' '300.12' '400']

In [18]:
data = np.array([100,200,'python',300.12, 400])
s = pd.Series(data)
print(s)
print(type(s))

print("Series to an array")
a = np.array(s.values.tolist())
print (a)
print(type(a))

0       100
1       200
2    python
3    300.12
4       400
dtype: object
<class 'pandas.core.series.Series'>
Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


#### 6. Write a Pandas program to sort a given Series.

In [19]:
panda_series = pd.Series([18,15,66,92,55,989])
print("Unsorted Pandas Series: \n", panda_series)

panda_series_sorted = panda_series.sort_values(ascending = True)
print("\nSorted Pandas Series: \n", panda_series_sorted)

Unsorted Pandas Series: 
 0     18
1     15
2     66
3     92
4     55
5    989
dtype: int64

Sorted Pandas Series: 
 1     15
0     18
4     55
2     66
3     92
5    989
dtype: int64


#### 7. Write a Pandas program to create a subset of a given series based on value and condition.

In [22]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


#### 8. Write a Pandas program to change the order of index of a given series.

In [20]:
# create numpy array
data = np.array(["Android dev",
                 "content writing",
                 "competitive coding"])
# create a series
total_series = pd.Series(data,
                         index = [1, 2, 3])
# reindexing of series
total_series = total_series.reindex(index
                                    = [3, 2, 1])
# show the series
total_series

3    competitive coding
2       content writing
1           Android dev
dtype: object

#### 9. Write a Pandas program to get the items of a given series not present in another given series.

In [21]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of sr1 not present in sr2:")
result = sr1[~sr1.isin(sr2)]
print(result)

Original Series:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


#### 10. Write a Pandas program to get the items which are not common of two given series.

In [23]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of a given series not present in another given series:")
sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))
result = sr11[~sr11.isin(sr22)]
print(result)

Original Series:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of a given series not present in another given series:
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64
